server:
  http_listen_port: 3200

distributor:
  receivers:
    zipkin: # Spring Boot(Micrometer)가 Zipkin 형식으로 보냅니다.
      endpoint: "0.0.0.0:9411"
    otlp:   # OpenTelemetry 표준 (미래 호환성용)
      protocols:
        http:
        grpc:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compaction_window: 1h
    max_block_bytes: 100_000_000
    block_retention: 1h
    compacted_block_retention: 10m

storage:
  trace:
    backend: local                     # 로컬 파일시스템 사용
    block:
      bloom_filter_false_positive: .05
      index_downsample_bytes: 1000
      encoding: zstd
    wal:
      path: /tmp/tempo/wal             # 임시 데이터 경로
    local:
      path: /tmp/tempo/blocks          # 영구 데이터 경로
    pool:
      max_workers: 100
      queue_depth: 10000
